### ISSUE TITLE
Not all possible export image formats are shown is export image.

### ISSUE THREAD

**Issue by whitecat** [prmr/JetUML#100]
To export in different format a user needs to know to add .jpg, .png, or .jpeg to the end of the file name.
This problem also exists for .svg but that is in review now.

**Comment by prmr** [comment]
Fixed as follows: if a user omits a file extension by has selected an image file filter, the software will silently add the extension.

**Comment by prmr** [comment]
When a file has a name, trying to choose the export format from the filter will still result in an error message.
