### ISSUE TITLE
Selection shortcut does not appear to work

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#109]
In the expanded Tool Panel the label for the selection button has, in parentheses: `Ctrl-G`, but this does not appear to do anything. We should make the accelerator work, or remove this part of the label. @JoelChev how was this supposed to work?

**Comment by JoelChev** [comment]
@prmr I'm not going to be near a computer this weekend, but I can dig into the code a bit on Monday. How it is supposed to work is that if you are using another tool, it will switch to the selection tool if you press CTRL-G. I'm not sure why this stopped working.

**Comment by prmr** [comment]
OK, since this would also have to be tested on Mac and the labels adapted, I will remove this feature for now. If someone wants to bring it back, the code is in `GraphPanel` of tagged version `0.7`
