### ISSUE TITLE
Overlapping Edges in Diagrams

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#114]
In all diagrams except sequence diagrams, adding multiple edges between two nodes invisibly stacks the edges. For class, object, state, and use case diagrams, this should not be possible. For sequence diagrams, the edge is re-drawn lower and lower: this should be fixed.
At the same time, the arrow end properties should be editable to make it possible to have bidirectional edges. We could even consider adding a bidirectional edge prototype to the toolbar.

**Comment by henray** [comment]
Oh. This issue was already reported right here.

**Comment by prmr** [comment]
There is quite a bit of work to do to improve the edges management, including creating specialized classes for aggregation, dependency, etc.

**Comment by prmr** [comment]
With the new design for the edge collection we can simply constrain diagrams (except sequence diagrams) to have a single type of edge between two nodes (one per direction).
