### ISSUE TITLE
Use Case editor system boundary

### ISSUE THREAD

**Issue by DevonOchman** [prmr/JetUML#116]
Use Case editor doesn't have the option to define a system boundary

**Comment by prmr** [comment]
This should be straightforward to implement by creating a new type of `ParentNode` (`SystemBoundaryNode`) and making all use case diagram nodes subclasses of `ChildNode`. It will be best to do this once the maintenance work is done on the graph framework. Added to the wishlist milestone.

**Comment by prmr** [comment]
Leave Use Case Diagrams flat until design rework.
