### ISSUE TITLE
Re-size objects not possible.

### ISSUE THREAD

**Issue by chichoch** [prmr/JetUML#147]
When selecting an object, the corners are visible in such a way that they should be resizeable, which they aren't. 

For usability-reasons, it would be beneficial if the user actually could re-size objects.

**Comment by prmr** [comment]
This is designed as a feature. Nodes are drawn with an automatically-determined size that matches their contents as well as possible, hence saving the need for an additional sizing gesture.
However, if the nodes don't draw properly, that would be something to fix. In that case, please post the steps to reproduce.
