### ISSUE TITLE
Solve Differing Geometry Question between Win/Linux platforms

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#181]
The tests don't pass on Linux due to slight differences in the calculation of geometric positions. Why?

**Comment by jiajunchen1995** [comment]
Two Possible Cause: 

1. Different Fonts used in different system. Even for Windows, some test cases failed on Windows 8.1 Chinese edition but all test are passed on Windows 10 English Edition. 
2. Different Rendering techniques used by different system.

**Comment by jiajunchen1995** [comment]
Just ran all the test again on Windows10 Chinese Edition, still have failures, which confirms that font does cause the problem.

**Comment by jiajunchen1995** [comment]
For Windows System, right click Project -> Properties -> Resource. Change Text File encoding to UTF-8 should fix the issues. Still trying to figure out how to fix for Mac and Linux.

**Comment by prmr** [comment]
The issue has been confirmed to be related to the font size. To solve the issue, we will no longer rely on the default system font, but hard-code a font to be used by the application.
