### ISSUE TITLE
Version Parsing for Java 10

### ISSUE THREAD

**Issue by SnoopDoop** [prmr/JetUML#201]
Java 9 introduces a new version scheme which breaks the existing version parsing.

An `ArrayIndexOutOfBoundsException` can now be raised.

This seems to happen because the method `ca.mcgill.cs.stg.jetuml.UMLEditor.isOKJVMVersion` tries to split "java.version" into an array of numbers. With JRE 1.8 the array would have length 3, but with JRE 9 the array has length 1 (as of October 16, 2017).

**Comment by prmr** [comment]
Very interesting, they changed the versioning scheme...

http://openjdk.java.net/jeps/223

**Comment by prmr** [comment]
Complete for Java 9 using the new `Version` class (although this would require the Java 9 JRE).
