### ISSUE TITLE
Change from internal frames to a tabbed panel to manage multiple graphs

### ISSUE THREAD

**Issue by EJBQ** [prmr/JetUML#21]
As part of this change:
* Refactor the toolbar to be a classic Swing toolbar
* Add labels to tools in the toolbar

**Comment by JoelChev** [comment]
@EJBQ For this issue, I will work with you, but I think I will work on adding labels and overall redesigning the toolbar during Milestone 4.

**Comment by EJBQ** [comment]
That sounds fine.

**Comment by JoelChev** [comment]
@EJBQ  @prmr The TabbedView is starting to come along! I invite you both to check it out and play with it a bit. I have yet to look into adding a splash screen (so on launch there is nothing on display, you have to add a tab to start interacting with JetUML). If there are any important features that I have not ported over yet, please let me know and I will look into them.

Some important changes:
-To close an open tab, you can either hit CTRL-W or go File->Close to close the current tab. If the GraphPanel in the current tab has been modified, it will launch a YES/NO OptionPane to confirm that you want to close the tab
-The Window menu of JetUML has been ripped out (as you don't need to resize windows or close them anymore).

For now, I am treating tabs as JInternalFrames (so either GrameFrames or an eventual WelcomeFrame splash tab as we discussed last week). If either of you feel that I should change this to a different Swing component (JPanel or something), please let me know and I can change this quickly. Thanks!

**Comment by JoelChev** [comment]
Alright, I have added X "Close" buttons to the Tabs in JetUML now. By clicking on an X, that designated tab will automatically close if it hasn't been modified, or will prompt the user with a message if it has been modified. Please let me know what you guys think of this feature, I can remove it if you don't like it.

**Comment by EJBQ** [comment]
This seems to be working correctly to me. The X works just like the closing normally, seems solid. I'll look into the code more, but the functionality seems solid.
