### ISSUE TITLE
Add Scrollbars in JavaFX UI

### ISSUE THREAD

**Issue by kkutschera** [prmr/JetUML#238]
In pull request #237, attempts were made to add scrollbars. In the last commit, https://github.com/prmr/JetUML/pull/237/commits/e41a80f55ea37b209d147cc24e280c0682c0693b, the following issues were still unresolved:
1) `ScrollPane` Viewing Area when `Canvas` is Resized
The `ScrollPane` viewing area is controlled by the scrollbar’s `hValue` and `vValue` properties. These properties are numbers between 0 and 1 that control the position of the scrollbars (for example, `hValue==1` means the rightmost position). Because of this, if `hValue==1` then the viewing area follows the rightmost edge of the canvas, otherwise the viewing area looks at whichever area is corresponding to the current `hValue` and `vValue` properties. This can be awkward, for example, if you set the scrollbar’s values to 1 and drag a node to the bottom-right corner of the viewing area, the viewing area follows, but if you take another node and drag it up to the top-left corner the viewing area, it doesn’t follow. From further research there doesn't seem to be a reliable way to get the viewport location and size of the `ScrollPane` since the provided `viewportBounds` property is not reliably updated when the viewport changes (it appears to only update if the window is resized and not if the scrollbars are moved)
2) Node Jumping to Meet Mouse
When dragging a node that is responsible for determining the graph bounds into the original viewing area of the `ScrollPane`, when the scrollbars disappear the node will jump to meet the position of the mouse (that is if the scrollbars are following the node’s position).
3) Responsiveness/Lag
There is more lag than with the Swing UI, which is believed to be due to canvas size.  The `Canvas` has to be created with a maximum size otherwise it does not appear at all.

Additionally, note that in https://github.com/prmr/JetUML/pull/237/commits/fec8554dbbbf6465cd4755f88f86f72d7708456b logic was added so that when the user drags the node past the canvas and drags it back there is no disconnect between the mouse location and the node location on the canvas.

**Comment by prmr** [comment]
From the above it looks like the following constraints are necessary:
- "Fixed" canvas size in that it cannot be resized dynamically. This is reasonable if we look at other drawing tools that have fixed page sizes;
- No turning on and off of scrollbars as a result of user manipulations of the graph.

Maybe a reasonable solution is to have a standard canvas size, and then automatically add scrollbars if the window size cannot handle it? If this works well we could then add a couple of other canvas size options. 

@kkutschera  what do you think of this plan?

**Comment by kkutschera** [comment]
I don't foresee any problems with that plan. Since the scrollbars are based on the size of the window, you shouldn't get any viewport issues like we had when trying to dynamically change the canvas size.

**Comment by prmr** [comment]
There is till work left to do on this one, namely:
* Automatically pan the scrollpane viewport as a selection is dragged outside the visible boundaries;
* Allow the user to set the canvas size.

However, these improvements should be open as new issues, since they will be much easier to implement after #257 is done.
