### ISSUE TITLE
Monitor selection in dual-screen setup

### ISSUE THREAD

**Issue by nassifm** [prmr/JetUML#252]
When using JetUML on a dual-screen setup, with the main window being on the second monitor, all dialogs and right-click menu appears in the first monitor, instead of where they should.

**Comment by prmr** [comment]
Calls to `Screen.getPrimary()` in the code need to be adjusted to account for the possibility of multiple displays.

**Comment by prmr** [comment]
The issue is caused by a mismatch between scene and screen coordinates. 

Method `DiagramFrameToolBar.showPopup` takes in a point argument supplied in scene coordinates and passes it to `ContextMenu,show` which expects a point in screen coordinates.
