### ISSUE TITLE
Potential System Incompatibilities on MacOS

### ISSUE THREAD

**Issue by arthursdays** [prmr/JetUML#280]
**Description**

The JetUML software will crash with diagrams unsaved in my computer. 

**Steps To Reproduce**

There is a case that it will certainly crash: If you run a software called "Duet", which is a software that makes your iPad as the secondary screen for your computer, at the same time you run JetUML. It will certainly crash within 5 mins. Sometimes it just crash as it likes. There is no rule to follow.

**Configuration**
OS: macOS 10.14.1
Java: 1.8.0_181-b13

**Comment by prmr** [comment]
I'll try to find a Mac User to reproduce this.

**Comment by prmr** [comment]
Can you try with this release and let us know if you experience the same problem: https://github.com/prmr/JetUML/releases/tag/v2.0.a

**Comment by arthursdays** [comment]
> Can you try with this release and let us know if you experience the same problem: https://github.com/prmr/JetUML/releases/tag/v2.0.a

This one seems to be good. I have not test the compatibility with "duet" yet. But the delete shortcut is all right. However, it is not compatible with the .jet file generated by the new software.

Thanks Prof. Robillard!

**Comment by prmr** [comment]
A separate issue #281 is created for the shortcut key problem.

**Comment by arthursdays** [comment]
Well the v2.0a works perfectly well even with "Duet display".

**Comment by prmr** [comment]
Now subsumed by #324
