### ISSUE TITLE
Shortcut key for 'delete' does not work on Mac

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#281]
**Description**
The shortcut key for delete does not do anything on Mac.

**Steps to reproduce**
1. Create a new class diagram
2. Create a new class node
3. Select the node
4. Press the 'delete' key - nothing happens

**Configuration**
 - JetUML Release: 2.2
 - OS + version: MacOS 10.14
 - Java version: "1.8.0_91
 
**Additional information**
Workaround: Use the `Edit` menu.

**Comment by J-J-C** [comment]
Found the issue, somehow the keystroke info changed to `BACKSPACE` instead of the original `BACK_SPACE` after 10.14 update

Here is the fix: https://github.com/prmr/JetUML/pull/282

However I am not sure if it is backward compatible. Need someone with an older MAC_OS version to verify that

**Comment by prmr** [comment]
Wow, I wonder what the point of that was. Thanks.
