### ISSUE TITLE
Diagram too large error prevents diagram opening

### ISSUE THREAD

**Issue by neilernst** [prmr/JetUML#286]
**Description**
Diagram too large for view dialog does not open diagram, but forces you to resize then re-open.

**Steps to reproduce**
1. Open a diagram saved on a higher resolution screen.
2. Error dialog (attached) shows dimensions are wrong and suggests resetting canvas size.
3. JetUML then refuses to open diagram. 

**Screenshots**
<img width="406" alt="screen shot 2018-11-18 at 18 31 31" src="https://user-images.githubusercontent.com/66286/48683203-d94ead80-eb60-11e8-864b-f5adcd32fa86.png">

**Configuration**
 - JetUML Release: 2.2
 - OS + version: Mac 10.14
 - Java version 1.8
 
**Additional information**
I expected the tool to automatically resize the canvas and add scroll bars. Since it knows the solution, it seems like the tool should just go ahead and change.

This is a particular problem when working on a laptop and opening multiple student projects, some of which are saved on larger screens.

**Comment by prmr** [comment]
This is a good suggestion. The rationale for the current behavior is twofold:
1. Canvas is not resizable
2. The size of the canvas was supposed to be a "view" attribute (in the sense of MVC), whereas the persistence feature was persisting only the model (i.e., the essential diagram components).

Given the annoyance that this causes, it might make sense to add the view size to the persistence file, and auto-size to it.

**Comment by neilernst** [comment]
that seems like the right approach to me - but how is minimum size defined? I think that the default (using Photoshop as an example) would be either "1:1" (and nodes might be off screen) or "fit", and for large diagrams, you see all the nodes, but perhaps at tiny sizes.

**Comment by prmr** [comment]
The (minimum) bounds are generated dynamically, using
```
Rectangle bounds = DiagramType.newViewInstanceFor(diagram).getBounds();
```
So that will be the minimum size. I'll add a margin to the left/bottom
