### ISSUE TITLE
Unable to paste any subgraph containing a PointNode

### ISSUE THREAD

**Issue by kkutschera** [prmr/JetUML#289]
**Description**
Unable to paste any subgraph containing a PointNode.

**Steps to reproduce**
1. Open any new diagram
2. Create a Note and attach a NoteEdge
3. Select the Note and attached NoteEdge
4. Copy and paste -> selection is not pasted

**Suspected Cause**
In the Clipboard, validNodeFor() is called to check if a paste is valid. Unfortunately, this only checks to see if the Node is contained in the diagram's node prototypes which PointNode is not included in for any diagram type.

**Comment by prmr** [comment]
Good catch. We could just return `true` for `PointNode` as the first statement. This oversight points to the need for better documentation and tests for `validPaste`
