### ISSUE TITLE
Click on OK button in properties dialog using 'Enter' key not working

### ISSUE THREAD

**Issue by stumash** [prmr/JetUML#292]
I can go to the Class Diagram builder and make an empty class. When I want to name it and add members and methods, I double click on it. This opens the 'properties dialog'.

In the properties dialog, I can use the 'tab' key to move between the different text input boxes and the OK button at the bottom of the dialog. However, I cannot click the OK button simply by hitting the enter key. It would be nice to be able to do this, since it seems to be possible in some, but not all, of the dialog boxes in the application.

**Configuration**
 - JetUML Release: `2.3`
 - OS + version:
```
$ uname -a

Linux storktop 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
 - Java version:
```
$ java -version

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by prmr** [comment]
This seems to work for me. With the focus in the attributes text area, I tab once and focus the OK button. Clicking Enter closes the dialog. If this does't work, could you please fill in the meta-data?

**Comment by prmr** [comment]
Strangely this worked on 2.3, but no longer on the current build.

**Comment by prmr** [comment]
As it turns out it was the space bar that fired the action event. Rigged it so Enter works as well.
