### ISSUE TITLE
Small typo in header comment for PropertySheet.getPropertyName

### ISSUE THREAD

**Issue by AllanWang** [prmr/JetUML#294]
https://github.com/prmr/JetUML/blob/60f2bf0c9a55852651fc8d7eff1aed3655d7bdb9/src/ca/mcgill/cs/jetuml/gui/PropertySheet.java#L253

**is** superclasses -> **in** superclasses

Not sure if you want us to submit patches for typos or not, but if you'd like to I can do that directly in the future

**Comment by prmr** [comment]
Yes, for typos in docs a pull request is most welcome.
