### ISSUE TITLE
Potentially unused tracker instance

### ISSUE THREAD

**Issue by AllanWang** [prmr/JetUML#295]
https://github.com/prmr/JetUML/blob/4243ba8a430f37b5970cb5f65b58dbd309ccf780/src/ca/mcgill/cs/jetuml/gui/PropertyEditorDialog.java#L72-L88

It appears that the tracker created at the beginning of this method is never actually used. It doesn't seem to be referenced externally and is never stopped. `stopTracking` occurs only once in production code for a separate tracker

**Comment by prmr** [comment]
Very suspicious. I will investigate. Thanks for reporting.
