### ISSUE TITLE
JavaVersionNotDetected when using Early Access build of Java

### ISSUE THREAD

**Issue by pashakondratyev** [prmr/JetUML#299]
**Description**
JetUML will not startup if using an Early Access Build of Java
"Caused by: ca.mcgill.cs.jetuml.application.JavaVersionNotDetectedException: Cannot parse version string: 1.8.0_202-ea"

**Steps to reproduce**
1. Have an Early Access Build of Java
2. Try to run JetUML

**Configuration**
 - JetUML Release: 2.3
 - OS + version: Mac OS 10.14.1
 - Java version - 1.8.202-ea
 
**Additional information**
The issue has to do with the "parseWithOldNumberingScheme" method in the JavaVersion class as when the string "1.8.202-ea" is parsed the third token becomes 202-ea which cannot be read as an integer.

**Comment by prmr** [comment]
We'll remove the version checking and put a notice on the website.
