### ISSUE TITLE
Change branding

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#3]
Change the tool name and branding information everywhere, respecting the copyrights.

**Comment by prmr** [comment]
This can be done in branch #27 since it'll touch every files as well.

**Comment by prmr** [comment]
The application is completely rebranded except that we should also convert the files extensions `violet` and `.*.violet` to `.jet` and `.*.jet`. @JoelChev, can you handle this one? You can commit this directly to branch 0027.

**Comment by JoelChev** [comment]
@prmr I just updated the file extensions. The files are also called Jet Files now in the menus and in the folder where they are saved.

**Comment by prmr** [comment]
Thanks. I renamed to JetUML files but otherwise this looks ready. Please do a bit of UI testing on branch 27  and send me mail as soon as you're satisfied with the version as releasable.
