### ISSUE TITLE
Application crashing on window de-focus

### ISSUE THREAD

**Issue by jkatofsky** [prmr/JetUML#322]
**Description**
Often (but not always) when I click away from JetUML to focus on another window, JetUML will crash.

**Steps to reproduce**
1. Be working on a JetUML project
2. Click away from the JetUML window, changing focus to another.
3. Often, JetUML will crash.

**Configuration**
 - JetUML Release: 2.5
 - OS + version: macOS Catalina v. 10.15.3 
 - Java version 8, Update 141

**Comment by prmr** [comment]
Thanks for reporting. It seems that [MacOS Catalina is not a certified system config](https://www.oracle.com/technetwork/java/javase/certconfig-2095354.html).

See also: [Javafx crashes on OSX on JRE 1.8](https://stackoverflow.com/questions/34711128)

Could this explain the problem? Are you able to run of a certified config to check whether the problem persists? 

There are a lot of incompatibilities with Mac, I'm working on some documentation to clarify this.

**Comment by prmr** [comment]
Related to: #300, #280

**Comment by prmr** [comment]
Now subsumed by #324
