### ISSUE TITLE
Missing documentation which Java version is needed to run 

### ISSUE THREAD

**Issue by datazuul** [prmr/JetUML#386]
I downloaded JetUml 3.0.2 jar.
Running it with Java 11

```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1deb10u1, mixed mode, sharing)

$ java --module-path <path-to-javafx>/javafx-sdk-11.0.2/lib --add-modules=javafx.controls,javafx.swing,java.desktop,java.prefs -jar <path-to-jar>/JetUML-3.0.2.jar
```

 causes Exception:

"JetUML has been compiled by a more recent version of the Java Runtime (class file version 58.0)"

I can not figure out what java version is needed to run.
Please document it.

**Comment by prmr** [comment]
Thanks for pointing out this oversight. You need Java 14.

**Comment by prmr** [comment]
It's documented here, but the version hadn't been updated. It is now up to date.
https://github.com/prmr/JetUML/blob/master/docs/install.md#thin-jar

**Comment by datazuul** [comment]
thank you for your fast answer!
The version is mentioned some lines above, too....
I think you missed the version update some lines above, still.

```
* **Thin Jar:** A small Java archive (jar) file that does _not_ include any of the dependencies. This option is available for experienced users who just want to download a tiny file and run it from the command-line. The thin jar is OS-independent but requires to have Java 11 or later *and* JavaFX 11 or later installed.
```
