### ISSUE TITLE
Can not move classes into packages

### ISSUE THREAD

**Issue by NumberC** [prmr/JetUML#412]
**Description**
When I attempt to move an already existing class into a package, the class does not go into the package. Instead, the class just overlaps with the package.

**Steps to reproduce**
1. Create a class
2. Create a package
3. Attempt to drag the class into the package

**Screenshots**
![ClassOverlapping](https://user-images.githubusercontent.com/47584014/107050960-dd932f80-6799-11eb-9383-8be3db6b211d.PNG)

**Configuration**
 - JetUML Release: 3.1
 - OS + version: Windows 10
 - Java version: 15.0.1

**Possible Solution**
I think this may be resolved by editing the `mouseReleased()` class in the `DiagramCanvasController` class. As of now, when you `DRAG_MOVE`, it only aligns the node to the grid, instead of adding the node as a child when applicable.

**Comment by prmr** [comment]
This feature is achieved through a different gesture (tapping the <kbd>shift</kbd> key). Please see the [user guide](https://www.jetuml.org/docs/user-guide.html) or enable the "Tip of the day" from the help menu.

![image](https://user-images.githubusercontent.com/6033492/107052551-cce3b900-679b-11eb-8f1d-c2344f07ec69.png)
