### ISSUE TITLE
Translating Children Nodes of Parent Nodes not working properly

### ISSUE THREAD

**Issue by JoelChev** [prmr/JetUML#42]
Steps to reproduce:
1. Use the lasso to select an Object Node with a Field Node inside it.
2. Try to move the selection around. The Field Node becomes temporarily "unhooked" from the Object Node and wiggles around in space while you move. It snaps back into place on release of the mouse.

This issue is caused by the translation being done twice for children nodes.

In GraphPanelMouseMotionListener, the code goes through the entire selection and does n.translate(dx, dy);.

However, the selection includes a parent node and all its children. However, the code for translate dynamically dispatches to AbstractNode.translate:

public void translate(double pDeltaX, double pDeltaY)
    {
        for(Node node : aChildren)
        {   
            node.translate(pDeltaX, pDeltaY);
        }
    }
which goes through all the children (again!) so basically the error is caused by the children nodes being translated twice.

**Comment by JoelChev** [comment]
@prmr @EJBQ  Alright, I just made some changes to the behavior of selecting Parent and Children nodes and I delegated translating children nodes of parents to the parent nodes themselves. Please let me know if either of you guys see anything that needs fixing. I wasn't able to find anything, but I can fix this up if necessary. Thanks!

**Comment by EJBQ** [comment]
It seems to work fine for me, I have no issues,

**Comment by JoelChev** [comment]
Alright. I will merge this branch in and close the issue.
