### ISSUE TITLE
Refactor the PersistenceTests

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#439]
There are a number of problems with the tests in `TestPersistenceService`:

* The tests do two things, test that the persistence works, and verify that the diagrams are drawn as expected. This should be split up.
* The part that verifies the diagram is not that useful. It just tests the bounds of all diagram elements. If something goes wrong, we don't really know what except that the pixels are off. We should test for specific expectations about the absolute and/or relative positions and dimensions of objects.
* The part that verifies the diagram is sensitive to the OS that the test runs on, because different system fonts lead to slightly different dimensions. See #346 and #400. It's a huge pain to have to adapt the tests for all OSes. The same oracle should be valid independently of the OS.

**Comment by delphinepilon** [comment]
Linking two additional commits: 
- 782dbd7fe7ee87098f2f7710a1924dcf3746aa67 
- 86122960323b506ca80a56d246d7cc995c65cd36
