### ISSUE TITLE
Menubar not responding correctly to mouse inputs

### ISSUE THREAD

**Issue by rp181135198** [prmr/JetUML#443]
**Description**
When I click on any menubar item, It shows me the dropdown menu till I relase the mouse button. Once I relase the mouse button, the dropdown menu disappears.

**Steps to reproduce**
1. Create new 'Class Diagram' diagram 
2. Click on 'File' (or any menubar item) and keep mouse button pressed
3. Relase the mouse button

**Screenshots**
1. Click on 'File' (or any menubar item) and keep mouse button pressed
![Click on 'File' (or any menubar item) and keep mouse button pressed](https://raw.githubusercontent.com/rp181135198/My-Gist-Files-Data/master/Image%20Data/jetumlErrorDiscussion/Click%20on%20Menu%20Item%20and%20keep%20mouse%20button%20pressed.png)

2. Relase the mouse button
![Relase the mouse button](https://raw.githubusercontent.com/rp181135198/My-Gist-Files-Data/master/Image%20Data/jetumlErrorDiscussion/Release%20the%20mouse%20button.png)

**Configuration**
 - JetUML Release: jetuml 3.3 [from aur package](https://aur.archlinux.org/packages/jetuml/)
 - OS: Manjaro Linux x86_64
 - Kernel: 5.10.68-1-MANJARO
 - DE: KDE Plasma 5.22.5
 - Java: [jdk-openjdk 16.0.2.u7-1](https://archlinux.org/packages/extra/x86_64/openjdk-doc/)
 
**Additional information**
I can't select any option from dropdown menu but keybord shortcuts are working fine.

**Comment by rp181135198** [comment]
Hi @prmr,
Actually I have tried both with dragging and without dragging my mouse but I got the same result.

Below is some results that you may find helpful..

 - Right click on `File` (and without dragging) released the mouse button
   => *Drop-down menu disappear*
 
 - Right click on `File`, drag mouse arrow to any drop-down menu option and release the mouse button
   => *Drop-down menu disappear and No command executed*
 
 - Right click on `File`, drag mouse arrow to any drop-down menu option and Left click
   => *Drop-down menu disappear and No command executed*

 - Right click on `File` and without releasing mouse button, used `up` and `down` arrow key to select any option from drop-down menu and hit `Enter` key
   => *Drop-down menu disappear and Selected command executed* ✔️

 - Used `Alt`+`F` and then without releasing any key, used `up` and `down` key to select any option from drop-down menu and hit `Enter` key
   => *Drop-down menu disappear and Selected command executed* ✔️

**Comment by prmr** [comment]
Thanks. These issues seem to be Linux-specific. We currently don't have a contributor on Linux, but I'll leave the issue open so we can look into it in the future.

**Comment by prmr** [comment]
Have you tried with Java 17?

**Comment by prmr** [comment]
Can't reproduce the issue on Linux Mint 21.1. Was probably due to an incompatible JDK.
