### ISSUE TITLE
Drag package content to bottom of viewport. Subsequence dragging misbehaves.

### ISSUE THREAD

**Issue by frentos** [prmr/JetUML#445]
**Description**
Drag a class nested in a package to the bottom of the viewport. Subsequent drag of any package content tracks mouse horizontally but not vertically. Expected behaviour: dragged content should track mouse movements.

**Steps to reproduce**
1. Create new 'Class' diagram 
2. Select "Package" tool
3. Click on canvas to create a package
4. Select "Class" tool
5. Click on canvas inside package boundary to create a class inside the package
6. Click on canvas inside package boundary to create a second class inside the package [now looks like fig1]
7. Select "Select" tool [ this step is optional; bug occurs if "Class" tool remains selected in the following steps ]
8. Click-and-drag one of the class objects [either will do] to the bottom of the viewport. Release mouse button. **Bottom edge of package is now slightly below the bottom edge of the viewport**. [attached fig2]
9. Click-and-drag the **other** class object. The selected class tracks left/right mouse movements, but creeps up so it is eventually no longer under the mouse cursor. Release the mouse button. [attached fig3] Attempts to retrieve the 'escaping' class object only make it move further up.
10. Click-and-drag the class object at the bottom of the screen. Like the other class, it tracks left-and-right but behaves as if fixed to the bottom of the viewport.

**Screenshots**
<img width="292" alt="fig1" src="https://user-images.githubusercontent.com/43694728/142062392-529d9f1f-ce5d-46f1-bc0a-6a058286ed1c.png">
<img width="599" alt="fig2" src="https://user-images.githubusercontent.com/43694728/142062397-93145fb7-7f23-4f8f-97fe-e936caaac9c3.png">
<img width="574" alt="fig3" src="https://user-images.githubusercontent.com/43694728/142062403-b8fe30b7-0744-476f-bc04-b8ab29bb43f3.png">

**Configuration**
 - JetUML Release: 3.3
 - OS + version: macOS Mojave version 10.14.6
 - Java version: Unknown. "java --show-version" reports  "openjdk 11.0.12 2021-07-20" from a command prompt, but goodness knows what java version the app-launching apparatus drags in.

**Comment by prmr** [comment]
Thanks for reporting. I can't reproduce the bottom edge part (step 8), but the rest is definitely evidence of a bug. We'll try to squeeze a fix into 3.4, the next release due by year end.
