### ISSUE TITLE
Improvements to the Edge Label Alignments

### ISSUE THREAD

**Issue by delphinepilon** [prmr/JetUML#446]
Some points could be improved in the layout and alignment of edge labels: 

1. In the state diagrams, state transition edges have a fixed line length when there are multiple words in the edge label. This can be inconvenient as it is less flexible than dynamic line lengths. 

https://user-images.githubusercontent.com/43301868/142290587-ed2247e8-bfb9-4879-8dd8-ba50ee76c063.mov

2. In class diagrams, segmented edges can have three labels. For horizontal segmented edges, the labels that are closest to the nodes are slightly shifted away from the node to clear the arrowhead. This is not the case for vertical segmented edges. Here, by horizontal segmented edge, I mean that the majority of segments are horizontal. 
<img width="720" alt="LackOfLabelAndArrowheadOverlap" src="https://user-images.githubusercontent.com/43301868/142290643-346ddb98-1f9e-4904-8ff5-4e2bfa1d84bc.png">

3. In class diagrams, the middle label of segmented edges can sometimes overlap the segments themselves which is not ideal as it can make the labels less readable.
<img width="720" alt="LabelAndSegmentOverlap" src="https://user-images.githubusercontent.com/43301868/142290662-21d2e944-60c5-4452-95a3-fd6b73a6eb7e.png">

**Comment by prmr** [comment]
Fixed with PR #447
