### ISSUE TITLE
Add macOS (Apple Silicon) release?

### ISSUE THREAD

**Issue by jiahao-c** [prmr/JetUML#454]
Currently, there's only a macOS(x64) release. Can we also have a macOS (Apple Silicon) release, so that M1 Mac users can run JetUML more smoothly?

**Comment by prmr** [comment]
Thanks for pointing this out. To ensure the integrity of the distribution, we currently can only offer self-contained binaries that are built by trusted contributors available at the time of release. But we will try to cast the net a bit wider for future releases, and hopefully include Apple Silicon.
