### ISSUE TITLE
Limit edges on start/end nodes in State Diagrams

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#47]
In State diagrams it should not be possible to add incoming edges to start nodes or outgoing edges from end nodes.

**Comment by JoelChev** [comment]
I have addressed this bug (commit to come soon), but in my current implementation I'm not allowing ANY edges to come from an end node or to go to a start node. Would you like me to make exceptions to this new rule for Note Connector edges?

**Comment by EJBQ** [comment]
Joel's code seems good, I just fixed a bug where edges from a start to a start node were allowed.
