### ISSUE TITLE
Resolve bugs with Sequence Diagrams in Copy/Cut+Paste

### ISSUE THREAD

**Issue by JoelChev** [prmr/JetUML#48]
This will likely be encompassed in the larger re-design of the Diagrams and the Parent-Child relationships of their Nodes that we will be tackling later on, but for now I just want to make sure that the issue is not forgotten.

Steps to reproduce:

1. Create a new sequence diagram with a Call Edge between two ImplicitParameterNodes. 
2. Copy/Cut it.
3. Paste it.

The Call Nodes behave erratically and don't seem to be fixed properly to their lifelines. Again, this is something that will likely be addressed in a larger redesign, but I just want to make sure it is addressed.

Relevant: https://github.com/prmr/JetUML/wiki/Parent-Child-Relation

**Comment by prmr** [comment]
I can no longer reproduce this bug. Was this fixed?

**Comment by JoelChev** [comment]
I'm still able to reproduce the bug following the steps above. In case it wasn't clear above, the diagram pastes properly, but the pasted diagram behaves erratically when you try to move it at all (edges and nodes don't seem to be properly fixed in place). I think a redesign of Sequence Diagrams will likely resolve this issue.
