### ISSUE TITLE
Addition of Inner Class Relationships in Class Diagrams

### ISSUE THREAD

**Issue by YovelB** [prmr/JetUML#489]
### Detailed Description

Currently UML Class Diagrams don't have a proper way to represent Inner classes. Because, UML needs to represent all languages.

Therefore, I suggest a basic relationship that can represents at least two types of inner classes (basic and nested).
The addition can be made more subtle by adding it to "edit" toolbar. While, not overpopulating the right side tools.
A relationship can be made of a crossed circle with an arrow pointing towards the inner class.

**for example:**
![template](https://user-images.githubusercontent.com/25065136/222984129-796e3498-56a5-4470-84e6-8e2e561e2b21.gif)

### Context

This change is important because it can highlight and explain better UML models. I like using nested classes and would like to represent it in my models.
Adding another relationships adds more complexity and understanding that needs to be explain to make clear models.
Other Java modelers can benefit from it by switching from other UML designers to JetUML. Because it is focused on the Java language features.

**Comment by prmr** [comment]
An interesting idea, but too specialized a scenario for the general sketching mission of the tool.
