### ISSUE TITLE
File format incompatibility

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#50]
There were some changes to the Graph framework that rendered the existing files unreadable (e.g., I can't load any data from the files in `/testdata`. What were these changes and how can we recover from them? I need to be able to make all the test diagram files I have work with the current version.

**Comment by EJBQ** [comment]
I think this was an issue with my changes to the Graph. This change preserves the changes I made and their benefits but makes the code work when the graph is not being loaded by the GraphPanel, which was an error with what I made. Saving and loading work correctly for me. @prmr, am I correct in seeing that your test files and are just blank graphs except for the class file?

**Comment by prmr** [comment]
Yup, I think this works.

**Comment by prmr** [comment]
merged into master
