### ISSUE TITLE
Typo in user guide - "Linking Note Elements"

### ISSUE THREAD

**Issue by ArthusWQZ** [prmr/JetUML#507]
**Description**
There seems to be a typo in the user guide, in category "Linking Note Elements".

The description says : "Use the note edge to link nodes to various parts of the diagram. Dragging a note edge from a target node to the note edge will link the note edge with the target node. Dragging a note edge from the note element will anchor the edge to a fixed point on the diagram."

However, shouldn't it be "Use the note edge to link **_notes_** to various parts of the diagram. Dragging a note edge from a target node to the note ~~edge~~ _element_ will link the note ~~edge~~ _element_ with the target node. Dragging a note edge from the note element will anchor the edge to a fixed point on the diagram."?

**Steps to reproduce**
1. Open the user guide
2. Scroll down to "Linking Note Elements"

**Screenshots**
![image](https://github.com/prmr/JetUML/assets/96388695/ff6c9eb0-9c3b-412c-b017-04b5acf227ae)

**Configuration**
 - JetUML Release: 3.6

**Comment by prmr** [comment]
Fixed and merged. This shows us corrected immediately on the website, but the version available as a tip of the day in the tool will only be visible in the next version.
