### ISSUE TITLE
Connection point calculation error in State Transition Diagram

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#547]
**Description**
When rendering two transition edges between two state nodes, if one of the nodes is in a very specific position in relation to the other node, the connection point for one of the two edges will be located at an incorrect position within the node. This can be observed for the bottom two corners.

**Steps to reproduce**
1. Create new State diagram .
2. Create two state nodes, join them by two edges in the same direction.
3. Carefully rotate one node around the other. The misplaced connection point can be observed by the edge flashing when the node is in the precise problematic position.

**Screenshots**
![image](https://github.com/prmr/JetUML/assets/6033492/fc689e71-f9ac-42bc-8a6d-6c1570314b2a)

**Configuration**
 - JetUML Release: 3.7
 
**Additional information**
Probably an issue in `StateTransitionEdgeRenderer`

**Comment by jkcoding7** [comment]
It appears that the incorrect position can occur at either side of the edge, but always in the north-west and north-east directions:

![image](https://github.com/prmr/JetUML/assets/113862811/126e1b99-e586-4bcc-830c-8b09744f83fc)
