### ISSUE TITLE
Toolbar Redesign

### ISSUE THREAD

**Issue by JoelChev** [prmr/JetUML#58]
Move the toolbar from the top of the GraphFrame and put it on the right side. The individual buttons on each individual diagram will remain the same, but functionality will be added to expand the toolbar to give each button a label if desired.

**Comment by JoelChev** [comment]
I have moved the toolbar to the right side of the JInternalFrame, but I am having some issues with the labels. @prmr, do you know where the actual icons for the Toolbar buttons are located? I'm not able to find them anywhere in the project and I want to debug the text placement. Thanks!

**Comment by prmr** [comment]
The "icons" are drawn, not rendered. `ToolBar.add` draws a small version of the graph element.

**Comment by JoelChev** [comment]
I'm currently playing around with adding text to the buttons in the Toolbar. I do not have a toggler to add/remove the text, but I will add that later. For now I just want to see what it looks like if I add text to the buttons in the Toolbar.

There are currently some issues though. Text displays fine for pretty much all the non-node buttons, but looks horrible on the buttons for node GraphElements. After playing around with this a bit, I think the issue I'm having is Nimbus LAF related. When I go without a LAF at all, the text of every button displays properly as expected. 

Going forward, should I keep the idea of adding text to buttons, or should I put the text in a JLabel or something beside the buttons? I'm curious what you two think. I encourage you both to check out my latest commit and let me know what you think of my first shot at a design. Thanks!

**Comment by JoelChev** [comment]
The ToolBar redesign is done for now. I'm waiting for @EJBQ to look into the Persistence failures before I merge it in, but it should be good to go!
