### ISSUE TITLE
Add edge list into nodes

### ISSUE THREAD

**Issue by EJBQ** [prmr/JetUML#62]
We need to make sure this is transient when saving, but can still be loaded back in

**Comment by JoelChev** [comment]
@EJBQ I'm looking into this a bit right now. I just want to clarify the intention here a bit. As it stands, if there is an edge that goes as follows A ---> B (where A is the origin node and B is the ending node), then it is only "added" through A, it's origin. Would you like the implementation to be set up in such a way that when you add an edge it is stored in the transient ArrayList of Node A AND Node B, or just Node A? Thanks!

**Comment by EJBQ** [comment]
Hmm. I think it would be better if it were added to both Node A and Node B. And it's simple enough to test if the node is the start or the end, so we can keep them all in one list.

Adding to both nodes let you remove a edge from the selection automatically that goes into the node you are removing, which is better.

**Comment by JoelChev** [comment]
I have implemented an initial design with two transient ArrayLists of Edges (origin and terminal edges). I can modify this if needed, but I need to do some work testing it for the time being.
