### ISSUE TITLE
Reorganize parent/child relationships

### ISSUE THREAD

**Issue by EJBQ** [prmr/JetUML#67]
I'm making this its own issue since I changed the other to deal with call nodes specifically. I'm just planning to try creating a ParentNode class for ObjectNode, PackageNode, and FieldNode to fall into.

**Comment by EJBQ** [comment]
So I'm having an issue with the merge that I haven't been able to figure out after a while of debugging. This does not occur in the master branch or the issue 67 branch but does when they're merged.

Steps to reproduce:
1) Create a Sequence Diagram
2) Create two ImplicitParameterNodes with one CallNode each
3) Make an edge from the left CallNode to the right one
4) Copy and Paste this entire setup

Expected output: An exact copy of what was copied
Actual Output: A second child of the CallNode without an edge to it

This also occurs when deleting the child and undoing the deletion, which leads me to believe it is not entirely related to the Clipboard, but I can't tell why it is happening. @prmr, @JoelChev, if either of you could take a look I would appreciate it. I've followed every step here in the code and can't figure out where this is happening.

**Comment by prmr** [comment]
I'm noticing this problem in the master branch
