### ISSUE TITLE
Create a Welcome Panel 

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#7]
The welcome panel should appear whenever there are no diagram, and should support creating new diagrams or opening recent files. Probably a good idea to add this after we switch over to the tabbed panel.

**Comment by prmr** [comment]
I already unhooked the about dialog from the launch sequence.

**Comment by JoelChev** [comment]
Hey guys, I just added a very rough outline of a WelcomeTab to JetUML. It will need some polishing (mostly just graphical stuff and some way to link in the functionality desired) though. For now, please check it out and let me know if you notice any buggy behavior. For now, it should be rendered on launch, or whenever the last open tab is closed. Also, the Welcome Tab cannot be closed manually when it is open, opening a new Tab is the only way to close it.

**Comment by JoelChev** [comment]
@prmr I have pushed a semi-finished version of the WelcomeTab. This version now has the icons and the functionality required of a WelcomeTab. The only issue however is that it isn't pretty (I'm going to need to ask you how to work with the Nimbus theme a bit to make it look better). For now, please play around with the commit and let me know what you think of the WelcomeTab!

Note: This commit is separate from the X Close button I just added to tabs in branch #21. I can integrate that functionality into this commit easily (I was thinking that the Welcome Tab won't have a close button however as it shouldn't be a closeable tab).

**Comment by EJBQ** [comment]
This seems to work too. It opens and closes properly at the correct time. I agree that the Welcome Tab should not have a close button though. How hard would that be to implement?

**Comment by JoelChev** [comment]
There are still issues here with trying to add a background to the WelcomeTab with the Nimbus theme enabled. I will show what I mean during our next meeting, but I will need some feedback before I close this issue.
