### ISSUE TITLE
Unit tests for class Clipboard

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#75]
There's a lot of complex untested logic there.

**Comment by prmr** [comment]
@JoelChev in `classDiagramEdgeEqual`, why are some properties (like `middleLabel`) used and others like `startLabel` not used?

**Comment by JoelChev** [comment]
I will have to look at it, but I think it may be because only certain edges have startLabels (I can't remember if this is a feature on all edges for every diagram type or not). If not, then it was just an oversight on my part.

**Comment by prmr** [comment]
Should the desired logic be that two edges are equal if all properties are equal? What is the method actually checking?

**Comment by prmr** [comment]
@EJBQ Why do the following node inherit from `ParentNode`?: `InterfaceNode`, `ActorNode`, `CallNode`, `ClassNode`, `FieldNode`?

**Comment by prmr** [comment]
Never mind, I see that having a parent and having a child is both supported by the `ParentNode` functionality.

**Comment by JoelChev** [comment]
@prmr I realized what the middleLabel check is used for. The testEdgeEquality method is really just used to determine the type of edge that needs to be pasted into the graph. Without calling this method, the clipboard class iterates through all of the possible edges for a given diagram and pastes a copy of each (as there is no simple .equals() method right now for a given edge type). Some edges (in Use Case Diagrams for instance) have a middle label like "<<include>>" which I need to compare against the list of Edges for a given diagram.

**Comment by prmr** [comment]
Rolled into #106 which requires a rewrite of the Clipboard to accommodate recursive parent-child cloning.
